version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres
      
  redis:
    container_name: "redis"
    image: docker.io/bitnami/redis:6.2
    command: /opt/bitnami/scripts/redis/run.sh --appendonly yes
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'

networks:
  postgres:
