export enum ExceptionCodes {
  // general error
  GENERAL_INTERNEL_SERVER_ERROR = 'GENERAL.INTERNEL_SERVER_ERROR',
  GENERAL_UNAUTHORIZED = 'GENERAL.UNAUTHORIZED',
  // validation error
  ARG_VALIDATION_ERROR = 'ARG.VALIDATION_ERROR',
}
